<?php

/**
 *------
 * BGA framework: © Gregory Isabelli <gisabelli@boardgamearena.com> & Emmanuel Colin <ecolin@boardgamearena.com>
 * theisleofcats implementation : © Guillaume Benny bennygui@gmail.com
 *
 * This code has been produced on the BGA studio platform for use on http://boardgamearena.com.
 * See http://en.boardgamearena.com/#!doc/Studio for more information.
 * -----
 */

const VALID_ROTATIONS = [0, 90, 180, 270];

// States: Main
const STATE_GAME_END = "gameEnd";
const STATE_GAME_END_ID = 99;

const STATE_ENTER_MAIN_PLAY_STATE = "STATE_ENTER_MAIN_PLAY_STATE";
const STATE_ENTER_MAIN_PLAY_STATE_ID = 100;

const STATE_MAIN_PLAY_STATE = "STATE_MAIN_PLAY_STATE";
const STATE_MAIN_PLAY_STATE_ID = 101;

const STATE_MAIN_PLAY_STATE_NEXT_PLAYER = "STATE_MAIN_PLAY_STATE_NEXT_PLAYER";
const STATE_MAIN_PLAY_STATE_NEXT_PLAYER_ID = 102;

// States: Private
const STATE_PRIVATE_INACTIVE_TURN = "STATE_PRIVATE_INACTIVE_TURN";
const STATE_PRIVATE_INACTIVE_TURN_ID = 1000;

const STATE_PRIVATE_CHOOSE_TILE_FROM_PLAYER_SUPPLY = "STATE_PRIVATE_CHOOSE_TILE_FROM_PLAYER_SUPPLY";
const STATE_PRIVATE_CHOOSE_TILE_FROM_PLAYER_SUPPLY_ID = 1001;

const STATE_PRIVATE_PLACE_TILE_IN_PARK = "STATE_PRIVATE_PLACE_TILE_IN_PARK";
const STATE_PRIVATE_PLACE_TILE_IN_PARK_ID = 1002;

const STATE_PRIVATE_CHOOSE_FROM_SUPPLY_BOARD = "STATE_PRIVATE_CHOOSE_FROM_SUPPLY_BOARD";
const STATE_PRIVATE_CHOOSE_FROM_SUPPLY_BOARD_ID = 1003;

const STATE_PRIVATE_PLACE_PLAYER_PARK = "STATE_PRIVATE_PLACE_PLAYER_PARK";
const STATE_PRIVATE_PLACE_PLAYER_PARK_ID = 1004;

const STATE_PRIVATE_PASS_TURN_CHOOSE_FROM_SUPPLY_BOARD = "STATE_PRIVATE_PASS_TURN_CHOOSE_FROM_SUPPLY_BOARD";
const STATE_PRIVATE_PASS_TURN_CHOOSE_FROM_SUPPLY_BOARD_ID = 1005;

const STATE_PRIVATE_CONFIRM_TURN = "STATE_PRIVATE_CONFIRM_TURN";
const STATE_PRIVATE_CONFIRM_TURN_ID = 1006;

const STATE_PRIVATE_PASS_TURN_NO_SHAPE = "STATE_PRIVATE_PASS_TURN_NO_SHAPE";
const STATE_PRIVATE_PASS_TURN_NO_SHAPE_ID = 1007;

// States: Private Try Mode
const STATE_PRIVATE_TRY_MODE_CHOOSE_TILE = "STATE_PRIVATE_TRY_MODE_CHOOSE_TILE";
const STATE_PRIVATE_TRY_MODE_CHOOSE_TILE_ID = 2001;

const STATE_PRIVATE_TRY_MODE_PLACE_TILE = "STATE_PRIVATE_TRY_MODE_PLACE_TILE";
const STATE_PRIVATE_TRY_MODE_PLACE_TILE_ID = 2002;

const STATE_PRIVATE_TRY_MODE_PLACE_PARK = "STATE_PRIVATE_TRY_MODE_PLACE_PARK";
const STATE_PRIVATE_TRY_MODE_PLACE_PARK_ID = 2003;

// Notifications
const NTF_MOVE_SHAPE_TO_PLAYER_SUPPLY = 'NTF_MOVE_SHAPE_TO_PLAYER_SUPPLY';
const NTF_MOVE_SHAPE_TO_PLAYER_PARK = 'NTF_MOVE_SHAPE_TO_PLAYER_PARK';
const NTF_MOVE_SHAPE_TO_SUPPLY_BOARD = 'NTF_MOVE_SHAPE_TO_SUPPLY_BOARD';
const NTF_SWAP_SHAPES = 'NTF_SWAP_SHAPES';
const NTF_CREATE_SHAPE = 'NTF_CREATE_SHAPE';
const NTF_DELETE_SHAPE = 'NTF_DELETE_SHAPE';
const NTF_CREATE_PARK = 'NTF_CREATE_PARK';
const NTF_DELETE_PARK = 'NTF_DELETE_PARK';
const NTF_REPLACE_PLAYER_PARK_AREA = 'NTF_REPLACE_PLAYER_PARK_AREA';
const NTF_REPLACE_SUPPLY_BOARD_PARKS = 'NTF_REPLACE_SUPPLY_BOARD_PARKS';
const NTF_UPDATE_SUPPLY_SHAPES_COUNT = 'NTF_UPDATE_SUPPLY_SHAPES_COUNT';
const NTF_UPDATE_SUPPLY_ACHIEVEMENTS_COUNT = 'NTF_UPDATE_SUPPLY_ACHIEVEMENTS_COUNT';
const NTF_DISPLAY_LAST_TURN = 'NTF_DISPLAY_LAST_TURN';
const NTF_MOVE_ACHIEVEMENT_TO_SUPPLY_BOARD = 'NTF_MOVE_ACHIEVEMENT_TO_SUPPLY_BOARD';
const NTF_MOVE_ACHIEVEMENT_TO_PLAYER = 'NTF_MOVE_ACHIEVEMENT_TO_PLAYER';
const NTF_UPDATE_SAVED_MOVE_NUMBER = 'NTF_UPDATE_SAVED_MOVE_NUMBER';

// Game Options
const GAME_OPTION_ACHIEVEMENT = 'GAME_OPTION_ACHIEVEMENT';
const GAME_OPTION_ACHIEVEMENT_ID = 100;
const GAME_OPTION_ACHIEVEMENT_VALUE_OFF = 0;
const GAME_OPTION_ACHIEVEMENT_VALUE_ON = 1;

const GAME_OPTION_VARIANT_PIT = 'GAME_OPTION_VARIANT_PIT';
const GAME_OPTION_VARIANT_PIT_ID = 101;
const GAME_OPTION_VARIANT_PIT_VALUE_OFF = 0;
const GAME_OPTION_VARIANT_PIT_VALUE_ON = 1;

const GAME_OPTION_HIDE_SCORE = 'GAME_OPTION_HIDE_SCORE';
const GAME_OPTION_HIDE_SCORE_ID = 102;
const GAME_OPTION_HIDE_SCORE_VALUE_SHOW = 0;
const GAME_OPTION_HIDE_SCORE_VALUE_HIDE = 1;

const GAME_OPTION_SOUVENIRSHOP = 'GAME_OPTION_SOUVENIRSHOP';
const GAME_OPTION_SOUVENIRSHOP_ID = 103;
const GAME_OPTION_SOUVENIRSHOP_VALUE_OFF = 0;
const GAME_OPTION_SOUVENIRSHOP_VALUE_ON = 1;

// User preferences
const USER_PREF_MODE_WARNING_ID = 150;
const USER_PREF_MODE_WARNING_VALUE_DISABLED = 0;
const USER_PREF_MODE_WARNING_VALUE_ENABLED = 1;

// Game Statistics
const STATS_PLAYER_SCORE_TOTAL = 'STATS_PLAYER_SCORE_TOTAL';
const STATS_PLAYER_SCORE_ANIMAL_HOUSE = 'STATS_PLAYER_SCORE_ANIMAL_HOUSE';
const STATS_PLAYER_SCORE_ENCLOSURE = 'STATS_PLAYER_SCORE_ENCLOSURE';
const STATS_PLAYER_SCORE_BEAR_STATUE = 'STATS_PLAYER_SCORE_BEAR_STATUE';
const STATS_PLAYER_SCORE_SOUVENIR_SHOP = 'STATS_PLAYER_SCORE_SOUVENIR_SHOP';
const STATS_PLAYER_SCORE_ACHIEVEMENT = 'STATS_PLAYER_SCORE_ACHIEVEMENT';
const STATS_PLAYER_SCORE_PLAYER_SUPPLY = 'STATS_PLAYER_SCORE_PLAYER_SUPPLY';
const STATS_PLAYER_NB_PLACED_SHAPE_GREEN = 'STATS_PLAYER_NB_PLACED_SHAPE_GREEN';
const STATS_PLAYER_NB_PLACED_SHAPE_ANIMAL_HOUSE = 'STATS_PLAYER_NB_PLACED_SHAPE_ANIMAL_HOUSE';
const STATS_PLAYER_NB_PLACED_SHAPE_ENCLOSURE = 'STATS_PLAYER_NB_PLACED_SHAPE_ENCLOSURE';
const STATS_PLAYER_NB_PLACED_SHAPE_BEAR_STATUE = 'STATS_PLAYER_NB_PLACED_SHAPE_BEAR_STATUE';
const STATS_PLAYER_NB_PLACED_SHAPE_SOUVENIR_SHOP = 'STATS_PLAYER_NB_PLACED_SHAPE_SOUVENIR_SHOP';
const STATS_PLAYER_NB_ACHIEVEMENT = 'STATS_PLAYER_NB_ACHIEVEMENT';
